name: Check all tests

on:
  status:

jobs:
  Check-statuses:
    runs-on: ubuntu-latest

    steps:
    - name: Check status
      run: |
        curl -s --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.sha }}/status \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | head -n 2 | tail -n 1 | grep "success"
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install STPM
      run: pip install git+https://github.com/SymbiFlow/symbiflow-tools-package-manager#egg=stpm
    - name: Get latest artifact name
      run: mkdir install && symbiflow_get_latest_artifact_url > install/latest
    - name: Upload artifact URL file
      uses: weslenng/gcp-storage-sync@master
      env:
        GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE  }}
        GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET  }}
        SOURCE_DIR: "install"

