name: Check all tests

on:
  status:

jobs:

  Check-statuses:
    runs-on: ubuntu-latest
    steps:

    - name: Check status
      id: check
      run: >-
        curl -fsSL
        -H 'Accept: application/vnd.github.v3+json'
        -H 'authorization: Bearer ${{ github.token }}'
        https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.sha }}/status
        | head -n 2
        | tail -n 1
        | grep "success"
        || echo '::set-output name=skip::true'

    - name: Set up Python
      if: steps.check.outputs.skip != 'true'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install STDM
      if: steps.check.outputs.skip != 'true'
      run: pip install git+https://github.com/SymbiFlow/symbiflow-tools-data-manager#egg=stdm

    - name: Get latest artifact name
      if: steps.check.outputs.skip != 'true'
      run: mkdir install && symbiflow_get_latest_artifact_url > install/latest

    - name: Upload artifact URL file
      if: steps.check.outputs.skip != 'true'
      uses: weslenng/gcp-storage-sync@master
      env:
        GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}
        SOURCE_DIR: "install"
