name: Check all tests

on:
  status:

jobs:

  Check-statuses:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ./.github/check-status
      with:
        token: ${{ github.token }}
        sha: ${{ github.event.sha }}

    - name: Upload artifact URL file
      if: steps.check.outputs.skip != 'true'
      uses: weslenng/gcp-storage-sync@master
      env:
        GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
        GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}
        SOURCE_DIR: "install"
