name: CI tests

on: [push, pull_request]

jobs:

  Test:
    if: ${{ !(github.event_name != 'pull_request' && github.actor == 'dependabot[bot]') }}
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]
    strategy:
      fail-fast: false
      matrix:
        test: ['docs', 'testarch', 'tests', 'ice40', 'xc7', 'xc7-vendor', 'xc7a200t', 'xc7a200t-vendor', 'ql']
    env:
      MAX_CORES: 80
      GHA_EXTERNAL_DISK: "tools"

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Execute test script
        run: stdbuf -i0 -o0 -e0 ./.github/ci/${{ matrix.test }}.sh

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: |
            **/results*.gz
            **/plot_*.svg

  Install:
    if: ${{ !(github.event_name != 'pull_request' && github.actor == 'dependabot[bot]') }}
    container: ubuntu:bionic
    runs-on: [self-hosted, Linux, X64]
    needs: Test

    env:
      MAX_CORES: 80
      GHA_EXTERNAL_DISK: "tools"
      GHA_SA: "gh-sa-f4pga-arch-defs-ci"
      UPLOAD_PACKAGES: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    steps:

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Execute test script
        run: stdbuf -i0 -o0 -e0 ./.github/ci/install.sh

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          path: |
            **/results*.gz
            **/plot_*.svg

  Automerge:
    needs: Test
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: Automerge dependabot PRs
    permissions:
      contents: write

    steps:

      - name: Auto-merge Dependabot PR
        run: GITHUB_TOKEN='${{ github.token }}' gh pr merge '${{ github.event.pull_request.html_url }}' --squash
